CUDA_VISIBLE_DEVICES=1 python3 clf.py \
	--model_path sssp.models.clf.clf_fixirrelevant \
	--train_path data/zhongao/tasks_hasnan_hierachy/Code_Zasd_ybsd/train.data.idx \
	--train_label_path data/zhongao/tasks_hasnan_hierachy/Code_Zasd_ybsd/train.data.idx \
	--train_unlabel_path data/zhongao/tasks_hasnan_hierachy/Code_Zasd_ybsd/train.data.idx \
	--valid_path data/zhongao/tasks_hasnan_hierachy/Code_Zasd_ybsd/valid.data.idx \
	--test_path data/zhongao/tasks_hasnan_hierachy/Code_Zasd_ybsd/test.data.idx \
	--vocab_path data/zhongao/tasks_hasnan_hierachy/Code_Zasd_ybsd/vocab.pkl \
	--save_dir results/tmp \
	--rnn_type GatedGRU \
	--vocab_size 15000 \
	--num_classes 16 \
	--init_from results/tmp4/rnn_test-16000
